postgres:
    image: postgres:11-alpine
    restart: always
    ports: 
        - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: strenggeheim
      POSTGRES_DB: guildwars
pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: toor
    links: 
        - postgres
