postgres:
    image: postgres:11-alpine
    restart: always
    ports: 
        - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: strenggeheim
      POSTGRES_DB: guildwars
pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: toor
    links: 
        - postgres
frontend:
    image: mewgrammer/gw2-companion:frontend
    restart: always
    ports: 
        - "80:80"
    links: 
        - backend
backend:
    image: mewgrammer/gw2-companion:backend
    restart: always
    ports: 
        - "8080:8080"
    links: 
        - postgres