rabbitmq:
  image: rabbitmq:management
  ports:
    - "5672:5672"
    - "15672:15672"
mongodb:
  image: mongo:jessie
  command: --smallfiles
  ports:
    - "27017:27017"
  environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
frontend:
  image: mewgrammer/gw2:frontend
  ports: 
    - "80:80"

    
  
