server:
  port: 8080

ribbon:
  ServerListRefreshInterval: 1000

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true